// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Cell = { letter: string, isBlack: boolean, number: number | null, isSelected: boolean, isHighlighted: boolean, };
