// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";

export type Clue = { number: number, direction: Direction, text: string, startRow: number, startCol: number, length: number, };
