// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from "./Cell";

export type Grid = { cells: Array<Array<Cell>>, width: number, height: number, };
